products/urls.py
from django.conf.urls import url
from django.urls import path
from products import views
from products.utils import get_cart_data

app_name = "products"

urlpatterns = [
    path("products/", views.DashboardClient.as_view(), name="products"),
    path("products_list/", views.ProductListFilter.as_view(), name="products_api"),
    path("product_detail/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product_cat/", views.ProductCategoryApi, name="product_api"),
    path('get_book_products/',views.get_cart_data, name="book-products"),
    path('cart/', views.CartSystem, name='get-cart-api'),
    path('main-redirect/', views.MainRedirect.as_view(), name="main-redirect"),
    path('checkout/', views.OrderView.as_view(), name="checkout"),
    path('checkout-success/', views.checkout_success, name="checkout-success"),
    path('order-success/', views.Order_Success, name="order-success"),
    path('reset_cart/',views.reset_cart, name="reset-cart"),
    path('delete_cart_product/<int:id>/',views.DeleteSingleProduct, name="delete-cart-product"),
    path('order-list-template/', views.OrderListTemplate, name="order-list-template"),
    path('order-list-api/',views.Order_List, name="order-list-api"),
    path('order-detail-template/<int:pk>/<str:order_id>', views.OrderDetailTemplate, name="order-detail-template"),
    path('order-detail-api/<int:pk>/<str:order_id>',views.OrderDetailApi, name="order-detail-api"),
    path('order-status/',views.OrderStatusUpdate, name="order-status"),
    path('order-status-form/<str:pk>/',views.OrderStatus, name="order-status-form"),
    path('product-api/',views.products_api, name="product-api"),
    path('product-list-template/',views.product_list_template, name="product-list-template"),
    path('create-product/',views.CreateProduct.as_view(), name="create-product"),
    path('delete-product/<int:pk>',views.ProductDelete, name="delete-product"),
    path('update-product/<int:pk>',views.UpdateProduct.as_view(), name="update-product"),
    # path('test/<str:id>/',views.test_view, name="test-view"),
    
    path('order-request-template/',views.OrderRequestTemplate, name="order-request-template"),
    path('order-request-api/',views.Order_Request, name="order-request-api"),
    
    path('pending-orders-list/',views.PendingOrderListTemplate, name="pending-order-template"),
    path('pending-orders-api/',views.PendingOrderApi, name="pending-order-api"),
    
    path('delievered-orders-list/',views.DelieveredOrderListTemplate, name="delievered-orders-template"),
    path('delievered-orders-api/',views.DelieveredOrderApi, name="delievred-orders-api"),
    
    path('order-request-form/',views.OrderRequestForm, name="order-request-form"),
    path('order-request-status/',views.OrderRequestStatus, name="order-request-status"),
    
    path('send-return-email/',views.SendReturnEmailList, name="send-return-email"),
    path('items-list/',views.ItemListApi, name='item-list-api'),
    path('send-email-form/',views.SendEmailForm, name='send-email-form'),
    path('send-email/', views.SendReturnEmail, name='send-email'),
    
    path('OrderCountGraphApi/',views.OrderCountGraphApi, name="order-graph-api"),
    
    #unused
    # path('api-overview/', views.api_overview, name="api-overview"),
    path('product-api/',views.Order_List, name="product-api"),
    path('product-detail/<str:pk>/',views.products_api, name="product-detail"),
]

rent_pro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('users.urls', namespace="users"), name="users"),
    # path('',RedirectView.as_view(url='/accounts/login/')),
    path('',RedirectView.as_view(url='/users/products/')),
    path('users/',include('products.urls', namespace="products"), name="products"),
    path('payments/',include('payments.urls', namespace="payments"), name="payments"),

    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("login/",auth_views.LoginView.as_view(template_name="login.html", redirect_authenticated_user=True), name="login" ),
    path("profile/",views.UpdateProfile.as_view(), name="profile" ),
    path("register/",views.RegisterUser.as_view(), name="register" ),
    path("logout/",auth_views.LogoutView.as_view(), name="logout" ),
    path("admin_dashboard/",views.AdminDashboard.as_view(), name="admin-dashboard"),
    path("user_list_template/",views.UserListTemplate.as_view(), name="user-list-template"),
    path("user_list/",views.User_List, name="user-list-api"),
    path("user_list_graph_api/",views.User_List_Graph, name="user-list-graph-api"),
]

products/forms.py
from django import forms
from django.db.models import fields
from django.db.models.enums import Choices
from django.forms import ModelForm
from products import models

class CategoryForm(ModelForm):
    class Meta:
        model = models.Product
        fields = ["prod_cat","prod_sub"]
        
class OrderForm(ModelForm):
    country = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    state = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    city = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    class Meta:
        model = models.Order
        fields = ["address","email","total_amount","deliever_at","country","state","city","zip_code",'your_bid_total']
        required = "__all__"
class OrderDelieveryStatusForm(ModelForm):
    class Meta:
        model = models.Order
        fields = ["status"]
        
class ProductForm(ModelForm):
    class Meta:
        model = models.Product
        exclude = ["timePeriod"]
        
class OrderStatusForm(ModelForm):
    class Meta:
        model=models.Order
        fields=['is_accepted']

products/views.py
import re
from django.core import paginator
from django.db.models import query
from django.http.response import Http404, HttpResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView, View
from django.views.generic import ListView,FormView,DetailView
from django.views.generic.edit import CreateView, UpdateView
from .models import Category, Product, Sub_Category,Cart, Order
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CategoryForm,OrderForm,OrderStatusForm,ProductForm,OrderStatusForm,OrderDelieveryStatusForm
from django.http import HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.utils.http import urlencode
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from django.core import serializers
from django.http import JsonResponse
from django.conf import settings
from django.core.mail import send_mail,EmailMultiAlternatives
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import CartSerializer, OrderGraphSerializer, ProductSerializer,OrderSerializer,OrderRequestSerializer
from django.core.exceptions import PermissionDenied
from django.db.models import Q
import uuid
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from notifications.signals import notify
from django.contrib.auth import get_user_model
from datetime import datetime
from datetime import timedelta
from django.db.models.functions import Cast, Trunc
from django.db.models import (Q, 
                            Sum, 
                            F, 
                            Max, 
                            Min,
                            Count,
                            Value,
                            ExpressionWrapper, 
                            DurationField,
                            DecimalField, 
                            DateField,
                            DateTimeField, 
                            TimeField)

# Create your views here.
User = get_user_model()
class MainRedirect(LoginRequiredMixin, View):
    def get(self,request, *args, **kwargs):
        print(self.request.user.user_role)
        if self.request.user.user_role=='Admin':
            return HttpResponseRedirect(reverse('users:admin-dashboard'))
        return HttpResponseRedirect(reverse('products:products'))    


class DashboardClient(FormView):
    template_name="product/dashboard_client.html"
    form_class = CategoryForm
    model = Category


    def get_querylist(self,**kwargs):
         query_list = {
                "product_list":kwargs['product_list'],
                "product":kwargs["product"]
            }
         return query_list

    def get_queryset(self):
        product_list = Product.objects.all()
        page = self.request.GET.get('page',1)
        paginator = Paginator(product_list, 10)
        query_list = {}
        try:
            query_list = self.get_querylist(product_list=product_list, product=paginator.page(page))

        except PageNotAnInteger:
            query_list=self.get_querylist(product_list=product_list, product=paginator.page(1))

        except EmptyPage:
            query_list=self.get_querylist(product_list=product_list, product=paginator.page(paginator.num_pages))

        return query_list
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("**querlist starts")
        print(self.get_queryset())
        print("**querylist ends")
        context["products"]=self.get_queryset()["product"]
        context["product_list"]=serializers.serialize("json",self.get_queryset()["product_list"])
        print(self.get_queryset())
        return context
    
    def post(self, request, *args, **kwargs):
        category = self.request.POST.get('category')
        sub_category = self.request.POST.get('sub_category')
        query_params = {
            'category':category,
            'sub_category':sub_category
        }   
        return HttpResponseRedirect(reverse_lazy('products:products_api')+f'?{urlencode(query_params)}')
    
    

def ProductCategoryApi(request):
        sub_category = Sub_Category.objects.values_list("category__cat_name","sub_category")
        print(sub_category)
        dct = dict((y,x) for x,y in sub_category)
        lst_dct = {}
        # lst_dct['Furniture'] = [k for k, v in dct.items() if v == 'Furniture']
        # lst_dct['ElectricAppliances'] = [k for k, v in dct.items() if v == 'ElectricAppliances']
        # lst_dct['FitnessEquipment'] = [k for k, v in dct.items() if v == 'FitnessEquipment']
        # lst_dct['Crockery'] = [k for k, v in dct.items() if v == 'Crockery']
        for k,v in dct.items():
            lst_dct[v] = [i for i,j in dct.items() if j == v]
        print(lst_dct)
        print("****************")
        print(dct)
        print("****************")
        print(lst_dct['Furniture'])
        
        return JsonResponse(lst_dct, safe=False)
          
class ProductListFilter(ListView):
    template_name="product/dashboard_client.html"
    def get_queryset(self):

        if self.request.method=="GET":
            query_set = {}
            cat = self.request.GET.get('category',None)
            sub_cat = self.request.GET.get('sub_category',None)
            
            if cat is not None and sub_cat is not None:
                query_set = Product.objects.filter(prod_cat__cat_name__contains=cat,prod_sub__sub_category__contains=sub_cat)
                return query_set
        return query_set
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["products"] = self.get_queryset()
        return context
    
class ProductDetailView(LoginRequiredMixin,DetailView):
    template_name="product/product_detail.html"
    model = Product
    
def get_cart_data(request):
    if request.method == 'POST':
        request_getdata = request.POST.get('data_dict', None)
        request_getdata = json.loads(request_getdata)
        print()
        cart_obj = Cart.objects.create(user=request.user)
        prod_obj = Product.objects.get(product_name=request_getdata['prod_name'])
        prod_obj.product_quantity = prod_obj.product_quantity - request_getdata['quantity']
        return_date = (datetime.now() + timedelta(days=request_getdata['days']+1)).strftime('%Y-%m-%d')
        cart_obj.product_name=request_getdata['prod_name']
        cart_obj.product_category=request_getdata['prod_cat']
        cart_obj.product_subcategory=request_getdata['prod_sub']
        cart_obj.total_price=request_getdata['total_price']
        cart_obj.quantity = request_getdata['quantity']
        cart_obj.your_bid_price = request_getdata['your_bid_price']
        cart_obj.order_id = "hello"
        cart_obj.return_date = return_date
        
        cart_obj.save()
        prod_obj.save()
        return JsonResponse({'url':reverse('products:get-cart-api')})
    
class OrderView(LoginRequiredMixin,View):
    form_class = OrderForm
    model = Order
    
    def get(self, *args, **kwargs):
        context = {
            'form':self.form_class,
            'total_amount':self.get_queryset()['total_price'],
            'total_bid_price':self.get_queryset()['total_bid_price'],
            'success_url':self.get_success_url()
        }
        return render(self.request, 'cart/checkout.html', context)
    
    def get_queryset(self,*args,**kwargs):
        qs = Cart.objects.filter(user=self.request.user, is_checkout=False).values('total_price','your_bid_price')
        context = {
        "total_price":0,
        "total_bid_price" :0
        }
        print(qs)
        for i in qs:
            context['total_price']+=i['total_price']
            context['total_bid_price']+=i['your_bid_price']
        return context

    def get_success_url(self,*args,**kwargs):
        return reverse_lazy('products:order-success')
    
@login_required
def Order_Success(request):
    if request.method == "POST":
        uni_id = uuid.uuid4()
        order_obj = Order.objects.create()
        print(uni_id)
        cart_obj = Cart.objects.filter(user=request.user,is_checkout=False).update(is_checkout=True,order_id=uni_id)
        order_obj.order_id = uni_id
        order_obj.user = request.user
        order_obj.email = request.POST.get('email')
        order_obj.address = request.POST.get('address')
        order_obj.total_amount = request.POST.get('total_amount')
        order_obj.deliever_at = request.POST.get('deliever_at')
        order_obj.country = request.POST.get('country')
        order_obj.state = request.POST.get('state')
        order_obj.city = request.POST.get('city')
        order_obj.zip_code = request.POST.get('zip_code')
        order_obj.your_bid_total = request.POST.get('your_bid_total')
        order_obj.save()
        user_obj = User.objects.get(user_role='Admin')
        print(user_obj)
        notify.send(request.user, recipient=user_obj, verb='Notification', description=f'Order Request from {request.user.email}')

        subject, from_email, to = 'Booking Request', settings.EMAIL_HOST_USER, request.user.email
        text_content = ''
        html_content = f'<h1>Booking Request Email</h1> <h2>{request.user} Your booking request has been sent<h2>'
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        subject, from_email, to = 'New Booking Request', settings.EMAIL_HOST_USER, settings.EMAIL_HOST_USER
        text_content = ''
        html_content = f'<h1>Booking Request Email</h1> <h2>You have received Booking Request from {request.POST.get("email")}<h2> <p><b>Order Id : </b>{uni_id}<p>'

products/templates/orders/order_requests_list.html
{% extends 'base.html' %} {% block title %}
<title>
    Order Request List
</title>
{% endblock %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}"> {% endblock %} {% block js %} {% endblock %} {% block body %}
<div class="preview-sec mt-3">
    <div class="row">
        <div class="col-lg-12 login-card">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="text-center pt-2">Orders Requests</h3>
                </div>
            </div>
            <hr>
            <div class="form-group col-lg-2">
                <img src="{% static 'images/more_options.png' %}" class="toggle-options" width="30%" height="50%" alt="" title="More Options" style="cursor: pointer;">
            </div>
            <div class="options">
                <div class="form-group col-lg-3">
                    <select name="date-cols" id="date-cols" class="form-control">
        <option value="hide" id="def">Select Date Column to Filter Records</option>
        <option value="8" id="startDate1">Ordered At</option>
        <option value="9" id="endDate1">Deliever At</option>
      </select>
                    <div id="date_filter" style="display: none;">
                        <div class="row">
                            <div class="col-lg-6">
                                <span id="date-label-from" class="date-label">From: </span><input class="date_range_filter date form-control" type="date" id="datepicker_from" />
                            </div>
                            <div class="col-lg-6">
                                <span id="date-label-to" class="date-label">To: <input class="date_range_filter date form-control"
                type="date" id="datepicker_to" />
          </div>
        </div>
      </div>
    </div>
                  <div class="form-group col-lg-2">
                      <select name="export-cols" id="exportLink" class="form-control">
                <option>Export Data</option>
                <option id="copy">Copy to clipboard</option>
                <option id="excel">Export as Excel</option>
                <option id="csv">Export as CSV</option>
                <option id="print">Export as Print</option>
              </select>
                  </div>
                  <!-- <div class="form-group col-lg-2">
                      <a class="btn submit-btn" id="imputation">Imputation</a>
                  </div> -->
              </div>
              <span class="loader my-3"></span>
                                <table id="dtorderlist" name="dtorderlist" class="display table table-hover table-borderless dt-responsive table-responsive-lg nowrap" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Order ID</th>
                                            <th>Email</th>
                                            <th>Ordered At</th>
                                            <th>Original Amount</th>
                                            <th>Total Order Bid</th>
                                            <th>Detail</th>
                                            <th>Order Request Status</th>
                                        </tr>
                                    </thead>

                                    <tbody id="orders-data">

                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>

                    <script type="text/javascript">
                        let dateCol = 8;
                        let expArr = [0, 1, 2, 3, 4, 5];
                        let tableId = '#dtorderlist';
                        apiUrl = '{% url "products:order-request-api" %}';
                        let user_role = "{{user.user_role}}"
                        console.log(user_role)
                        let responseArrCols = [{
                            "data": "order_id"
                        }, {
                            "data": "email"
                        }, {
                            "data": "ordered_at",
                            "render": function(data, type) {
                                if (type === "sort") {
                                    return data;
                                } else {
                                    data = moment.utc(data, "YYYY-MM-DD HH:mm").tz('Pakistan/Karachi')
                                    data = moment(data).format("L HH:mm")
                                    return data;
                                }
                            }
                        }, {
                            "data": "total_amount",
                            "render": function(data, type) {
                                return data + " PKR"
                            }
                        }, {
                            "data": "your_bid_total",
                            "render": function(data, type) {
                                if (data != null) {
                                    return data + " PKR"
                                } else {
                                    return "-"
                                }
                            }
                        }, {
                            "data": "user",
                            "render": function(data, type, row) {
                                console.log(row.order_id);
                                let url_mask = "{% url 'products:order-detail-template' 123 456 %}".replace('123', data).replace('456', row.order_id);
                                return '<a href=' + url_mask + '>Details</a>'
                            }
                        }, {
                            mRender: function(data, type, row) {
                                let reqUrl = '{% url "products:order-request-form" %}'
                                if (user_role == "Admin") {
                                    return `<a class="table-edit" href=${reqUrl}?order_id=${row['order_id']}&email=${row['email']}>Order Request</a>`
                                } else {
                                    return data
                                }
                                // let editUrl = '{% url "products:update-product" 123 %}'.replace('123', row['order_id'])
                            }
                        }, ]
                        loadRecordsInDataTable(dateCol, expArr, apiUrl, responseArrCols, tableId);
                    </script>
                    {% endblock %}

products/templates/orders/orders_list.html
{% extends 'base.html' %} {% block title %}
<title>
    Order List
</title>
{% endblock %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}"> {% endblock %} {% block js %} {% endblock %} {% block body %}
<div class="preview-sec mt-3">
    <div class="row">
        <div class="col-lg-12 login-card mx-auto">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center pt-2 mt-2">Orders</h2>
                </div>
            </div>
            <hr>
            <div class="form-group col-lg-2">
                <img src="{% static 'images/more_options.png' %}" class="toggle-options" width="30%" height="50%" alt="" title="More Options" style="cursor: pointer;">
            </div>
            <div class="options">
                <div class="form-group col-lg-3">
                    <select name="date-cols" id="date-cols" class="form-control">
            <option value="hide" id="def">Select Date Column to Filter Records</option>
            <option value="8" id="startDate1">Ordered At</option>
            <option value="9" id="endDate1">Deliever At</option>
          </select>
                    <div id="date_filter" style="display: none;">
                        <div class="row">
                            <div class="col-lg-6">
                                <span id="date-label-from" class="date-label">From: </span><input class="date_range_filter date form-control" type="date" id="datepicker_from" />
                            </div>
                            <div class="col-lg-6">
                                <span id="date-label-to" class="date-label">To: <input class="date_range_filter date form-control"
                    type="date" id="datepicker_to" />
              </div>
            </div>
          </div>
        </div>
                      <div class="form-group col-lg-2">
                          <select name="export-cols" id="exportLink" class="form-control">
                    <option>Export Data</option>
                    <option id="copy">Copy to clipboard</option>
                    <option id="excel">Export as Excel</option>
                    <option id="csv">Export as CSV</option>
                    <option id="print">Export as Print</option>
                  </select>
                      </div>
                      <!-- <div class="form-group col-lg-2">
                          <a class="btn submit-btn" id="imputation">Imputation</a>
                      </div> -->
                  </div>
                  <span class="loader my-3"></span>
                                <table id="dtorderlist" name="dtorderlist" class="display table table-hover table-borderless dt-responsive table-responsive-lg nowrap" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Order ID</th>
                                            <th>Address</th>
                                            <th>Email</th>
                                            <th>Amount</th>
                                            <th>Country</th>
                                            <th>State</th>
                                            <th>City</th>
                                            <th>Zip Code</th>
                                            <th>Ordered At</th>
                                            <th>Deliever At</th>
                                            <th>Delievery Status</th>
                                            <th>Detail</th>
                                            <th>Process Payment</th>
                                            <th>Request Status</th>
                                        </tr>
                                    </thead>

                                    <tbody id="orders-data">

                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>

                    <script type="text/javascript">
                        let dateCol = 8;
                        let expArr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
                        let tableId = '#dtorderlist';
                        apiUrl = '{% url "products:order-list-api" %}';
                        let user_role = "{{user.user_role}}"
                        let responseArrCols = [{
                            "data": "order_id"
                        }, {
                            "data": "address"
                        }, {
                            "data": "email"
                        }, {
                            "data": "your_bid_total",
                            "render": function(data, type, row) {
                                return 'pkr ' + data;
                            }
                        }, {
                            "data": "country"
                        }, {
                            "data": "state"
                        }, {
                            "data": "city"
                        }, {
                            "data": "zip_code"
                        }, {
                            "data": "ordered_at",
                            "render": function(data, type) {
                                if (type === "sort") {
                                    return data;
                                } else {
                                    data = moment.utc(data, "YYYY-MM-DD HH:mm").tz('Pakistan/Karachi')
                                    data = moment(data).format("L HH:mm")
                                    return data;
                                }
                            }
                        }, {
                            "data": "deliever_at",
                            "render": function(data, type) {
                                if (data !== null) {
                                    if (type === "sort") {
                                        return data;
                                    } else {
                                        data = moment.utc(data, "YYYY-MM-DD").tz('Pakistan/Karachi')
                                        data = moment(data).format("L")
                                        return data;
                                    }
                                } else {
                                    return "null";
                                }

                            }
                        }, {
                            "data": "status",
                            "render": function(data, type, row) {
                                console.log("****************************")
                                console.log(row)
                                if (user_role == "Admin" && row['payment_process'] == "Received") {
                                    let url_mask = "{% url 'products:order-status' %}";
                                    url_mask = `${url_mask}?order_id=${row.order_id}`
                                    return '<a href=' + url_mask + '>' + data + '</a>'
                                } else {
                                    return data;
                                }

                            }
                        }, {
                            "data": "user",
                            "render": function(data, type, row) {
                                console.log(row.order_id);
                                let url_mask = "{% url 'products:order-detail-template' 123 456 %}".replace('123', data).replace('456', row.order_id);
                                return '<a href=' + url_mask + '>Details</a>'
                            }
                        }, {
                            "data": "payment_process",
                            "render": function(data, type, row) {
                                return data.charAt(0).toUpperCase() + data.slice(1);

                            }

                        }, {
                            "data": "is_accepted"
                        }];

                        loadRecordsInDataTable(dateCol, expArr, apiUrl, responseArrCols, tableId);
                    </script>
                    {% endblock %}