products/urls.py
from django.conf.urls import url
from django.urls import path
from products import views
from products.utils import get_cart_data

app_name = "products"

urlpatterns = [
    path("products/", views.DashboardClient.as_view(), name="products"),
    path("products_list/", views.ProductListFilter.as_view(), name="products_api"),
    path("product_detail/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product_cat/", views.ProductCategoryApi, name="product_api"),
    path('get_book_products/',views.get_cart_data, name="book-products"),
    path('cart/', views.CartSystem, name='get-cart-api'),
    path('main-redirect/', views.MainRedirect.as_view(), name="main-redirect"),
    path('checkout/', views.OrderView.as_view(), name="checkout"),
    path('checkout-success/', views.checkout_success, name="checkout-success"),
    path('order-success/', views.Order_Success, name="order-success"),
    path('reset_cart/',views.reset_cart, name="reset-cart"),
    path('delete_cart_product/<int:id>/',views.DeleteSingleProduct, name="delete-cart-product"),
    path('order-list-template/', views.OrderListTemplate, name="order-list-template"),
    path('order-list-api/',views.Order_List, name="order-list-api"),
    path('order-detail-template/<int:pk>/<str:order_id>', views.OrderDetailTemplate, name="order-detail-template"),
    path('order-detail-api/<int:pk>/<str:order_id>',views.OrderDetailApi, name="order-detail-api"),
    path('order-status/',views.OrderStatusUpdate, name="order-status"),
    path('order-status-form/<str:pk>/',views.OrderStatus, name="order-status-form"),
    path('product-api/',views.products_api, name="product-api"),
    path('product-list-template/',views.product_list_template, name="product-list-template"),
    path('create-product/',views.CreateProduct.as_view(), name="create-product"),
    path('delete-product/<int:pk>',views.ProductDelete, name="delete-product"),
    path('update-product/<int:pk>',views.UpdateProduct.as_view(), name="update-product"),
    # path('test/<str:id>/',views.test_view, name="test-view"),
    
    path('order-request-template/',views.OrderRequestTemplate, name="order-request-template"),
    path('order-request-api/',views.Order_Request, name="order-request-api"),
    
    path('pending-orders-list/',views.PendingOrderListTemplate, name="pending-order-template"),
    path('pending-orders-api/',views.PendingOrderApi, name="pending-order-api"),
    
    path('delievered-orders-list/',views.DelieveredOrderListTemplate, name="delievered-orders-template"),
    path('delievered-orders-api/',views.DelieveredOrderApi, name="delievred-orders-api"),
    
    path('order-request-form/',views.OrderRequestForm, name="order-request-form"),
    path('order-request-status/',views.OrderRequestStatus, name="order-request-status"),
    
    path('send-return-email/',views.SendReturnEmailList, name="send-return-email"),
    path('items-list/',views.ItemListApi, name='item-list-api'),
    path('send-email-form/',views.SendEmailForm, name='send-email-form'),
    path('send-email/', views.SendReturnEmail, name='send-email'),
    
    path('OrderCountGraphApi/',views.OrderCountGraphApi, name="order-graph-api"),
    
    #unused
    # path('api-overview/', views.api_overview, name="api-overview"),
    path('product-api/',views.Order_List, name="product-api"),
    path('product-detail/<str:pk>/',views.products_api, name="product-detail"),
]

rent_pro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('users.urls', namespace="users"), name="users"),
    # path('',RedirectView.as_view(url='/accounts/login/')),
    path('',RedirectView.as_view(url='/users/products/')),
    path('users/',include('products.urls', namespace="products"), name="products"),
    path('payments/',include('payments.urls', namespace="payments"), name="payments"),

    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("login/",auth_views.LoginView.as_view(template_name="login.html", redirect_authenticated_user=True), name="login" ),
    path("profile/",views.UpdateProfile.as_view(), name="profile" ),
    path("register/",views.RegisterUser.as_view(), name="register" ),
    path("logout/",auth_views.LogoutView.as_view(), name="logout" ),
    path("admin_dashboard/",views.AdminDashboard.as_view(), name="admin-dashboard"),
    path("user_list_template/",views.UserListTemplate.as_view(), name="user-list-template"),
    path("user_list/",views.User_List, name="user-list-api"),
    path("user_list_graph_api/",views.User_List_Graph, name="user-list-graph-api"),
]

products/models.py
from django.db import models
from django.shortcuts import render
from django.urls.base import reverse
from users.models import User
import uuid
from datetime import datetime
from django.db.models.signals import post_save,m2m_changed
from django.db import transaction
from django.dispatch import receiver

# Create your models here.

class Category(models.Model):
    CATEGORY = (
        ("Furniture","Furniture"),
        ("ElectricAppliances","ElectricAppliances"),
        ("FitnessEquipment","FitnessEquipment"),
        ("Crockery","Crockery"),        
    )
    cat_name = models.CharField(max_length=255,null=True,blank=True,choices=CATEGORY)
    
    def __str__(self):
        return self.cat_name

class Sub_Category(models.Model):    
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, related_name="categories")
    sub_category = models.CharField(max_length=255,null=True, blank=True)

    def __str__(self):
        return self.sub_category
    
class Product(models.Model):
    prod_cat = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)
    prod_sub = models.ForeignKey(Sub_Category, null=True, blank=True, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255, null=True, blank=True)
    product_desc = models.TextField(max_length=255, null=True, blank=True)
    prod_img = models.ImageField(upload_to="item_pics", default="nothing.jpg")
    product_price = models.FloatField(max_length=255, null=True, blank=True)
    product_quantity = models.IntegerField(null=True, blank=True)
    timePeriod = models.IntegerField(null=True,default=1)

    def __str__(self):
        return self.product_name
    
class Cart(models.Model):
    order_id = models.CharField(max_length=255, null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    product_name = models.CharField(max_length=255,null=False, blank=False)
    product_category = models.CharField(max_length=255,null=False, blank=False)
    product_subcategory = models.CharField(max_length=255,null=False, blank=False)
    total_price = models.IntegerField(null=True, blank=True)
    your_bid_price = models.IntegerField(null=True, blank=True)
    is_checkout = models.BooleanField(default=False)
    quantity = models.IntegerField(null=True)
    return_date = models.DateField(null=True, blank=True)
    return_email_sent = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.id)
    
    
    
class Order(models.Model):
    ORDER_STATUS = (
        ("Pending","pending"),
        ("Delievered","delievered"),
        ("Out for delievery","out for delievery")
        )
    
    REQUEST_STATUS = (
        ("Pending","pending"),
        ("Accept","accept"),
        ("Reject","reject")
        )
    PAYMENT_STATUS = (
    ("pending","Pending"),
    ("received","Received"),
    )

    order_id = models.CharField(max_length=255, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    ordered_at = models.DateTimeField(auto_now_add=True,auto_now=False)
    deliever_at = models.DateField(null=True, blank=True)
    total_amount = models.FloatField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=255,null=True, blank=True, choices=ORDER_STATUS, default="Pending")
    country = models.CharField(max_length=255,null=True,blank=True)
    state = models.CharField(max_length=255,null=True,blank=True)
    city = models.CharField(max_length=255,null=True,blank=True)
    zip_code = models.CharField(max_length=255,null=True,blank=True)
    your_bid_total = models.IntegerField(null=True, blank=True) 
    is_accepted = models.CharField(max_length=30,null=False,blank=False, choices=REQUEST_STATUS, default="Pending")
    payment_process = models.CharField(max_length=30,null=False,blank=False, choices=PAYMENT_STATUS, default="pending")
    
    def __str__(self):
        return str(self.order_id)
        

products/forms.py
from django import forms
from django.db.models import fields
from django.db.models.enums import Choices
from django.forms import ModelForm
from products import models

class CategoryForm(ModelForm):
    class Meta:
        model = models.Product
        fields = ["prod_cat","prod_sub"]
        
class OrderForm(ModelForm):
    country = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    state = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    city = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    class Meta:
        model = models.Order
        fields = ["address","email","total_amount","deliever_at","country","state","city","zip_code",'your_bid_total']
        required = "__all__"
class OrderDelieveryStatusForm(ModelForm):
    class Meta:
        model = models.Order
        fields = ["status"]
        
class ProductForm(ModelForm):
    class Meta:
        model = models.Product
        exclude = ["timePeriod"]
        
class OrderStatusForm(ModelForm):
    class Meta:
        model=models.Order
        fields=['is_accepted']

products/templates/cart/cart.html
{% extends 'base.html' %} {% block title %}
<title>Cart</title>
{% endblock %}{% block body %} {% if orders.count > 0 %}
<div class="row">
    <div class="col-lg-12">
        <div class="text-right">
            <a href="{% url 'products:products' %}" class="btn btn-primary continue-book">Continue Booking <i class="fa fa-shopping-cart text-light" aria-hidden="true"></i> </a>
            <a href="{% url 'products:reset-cart' %}" class="btn btn-danger reset-card">Reset Cart  <i class="fas fa-trash text-light"></i></a>
            <a href="{% url 'products:checkout' %}" class="btn btn-success checkout-btn">Go To Checkout <i class="fa fa-credit-card-alt text-light"></i></a>

        </div>
    </div>
</div>
{% endif %} {% for order in orders %} {% if count > 0 %}
<div class="col-lg-10 mx-auto">
    <div class="card prod-card login-card my-3">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-3">
                    <h5><b>Product Name</b>
                    </h5>
                    <p class="card-text mt-3">{{order.product_name}}</p>
                </div>
                <div class="col-lg-2">
                    <h5><b>Quantity</b></h5>
                    <p class="card-text mt-3">{{order.quantity}}</p>
                </div>
                <div class="col-lg-2">
                    <h5><b>Product Price</b></h5>
                    <p class="prod-price mt-3">pkr <span class="price">{{order.total_price}}</span></p>
                </div>
                <div class="col-lg-2">
                    <h5><b>Your Bid Price</b></h5>
                    <p class="bid-price mt-3">pkr <span class="bid_price">{{order.your_bid_price}}</span></p>
                </div>
                <div class="col-lg-2">
                    <h5><b>Delete Product</b></h5>
                    <a href="{% url 'products:delete-cart-product' order.id %}"><i class="fas fa-trash text-center text-danger "></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %} {% endif %} {% endfor %} {% if orders.count > 0 %}
<div class="col-lg-6 mx-auto">
    <div class="card prod-card login-card my-3">
        <div class="card-body">
            <div class="row">
                <!-- <div class="col-lg-6"></div> -->
                <div class="col-lg-6">
                    <h3><b>Product Price</b></h3>
                    <p class="prod-price mt-3">PKR <span class="total_price cart_price"></span></p>
                </div>
                <div class="col-lg-6">
                    <h3><b>Your Bid Price</b></h3>
                    <p class="bid-price mt-3">PKR <span class="bid_total_price cart_price"></span></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<h1 class="text-center">No Items Found In Cart</h1>
{% endif %}
<script>
    $(document).ready(function() {
        let price = document.querySelectorAll(".price")
        let bid_price = document.querySelectorAll(".bid_price")
        let total_price = 0;
        let bid_total = 0;
        for (var i = 0; i < price.length; i++) {
            total_price += Number(price[i].textContent)
        }
        for (var j = 0; j < bid_price.length; j++) {
            console.log(bid_price[j].textContent)
            bid_total += Number(bid_price[j].textContent)
        }
        $(".total_price").text(total_price)
        $(".bid_total_price").text(bid_total)

        function preventBack() {
            window.history.forward();
        }
        window.onunload = function() {
            null;
        };
        setTimeout("preventBack()", 0);
    })
</script>
{% endblock %}

products/templates/cart/checkout.html
{% extends 'base.html' %} {% block title %}
<title>Checkout Details</title>
{% endblock %}{% block body %}
<div class="row">
    <div class="col-lg-5 mx-auto">
        <div class="card prod-card login-card">
            <div class="card-header">
                <h4>Shipping Details</h4>
            </div>
            <div class="card-body">
                <form action="{{success_url}}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="email">Email address</label> {{form.email}}
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div class="form-group">
                        <label for="address">Shipping Address</label> {{form.address}}
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="total_amount">Total Amount</label> {{form.total_amount}}
                            </div>
                            <div class="col-lg-4">
                                <label for="total_bid_price">Total Bid Price</label> {{form.your_bid_total}}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="country">Country</label> {{form.country}}
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="state">State</label> {{form.state}}
                            </div>
                            <div class="col-lg-4">
                                <label for="city">City</label> {{form.city}}
                            </div>
                            <div class="col-lg-4">
                                <label for="zip_code">Zip Code</label> {{form.zip_code}}
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="deliever_at">Delievery Date</label> {{form.deliever_at}}
                        <small id="emailHelp" class="form-text text-muted">Make sure you give atleast 3 days headsup for the delievery.</small>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary book-btn">Checkout</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<script>
    let dt = new Date()
    let mn = dt.getMonth() + 1
    let date = dt.getDate() + 3
    date = date > 10 ? date : '0' + date
    mn = mn > 10 ? mn : '0' + mn
    dt = dt.getFullYear() + '-' + mn + '-' + date

    $("#id_email").val("{{user.email}}")
    $("#id_email, #id_total_amount, #id_your_bid_total").attr("readonly", true)
    $("#id_total_amount").val("{{total_amount}}")
    $("#id_your_bid_total").val("{{total_bid_price}}")
    $("#id_deliever_at").removeAttr("type")
    $("#id_deliever_at").attr("type", "date")
    $("input,select").addClass("form-control")
    $("#id_deliever_at").attr("min", dt)
    $("select[name=country], select[name=state], select[name=city]").removeAttr("id")
    $("select[name=country]").attr("id", "countryId")
    $("select[name=country]").addClass("countries")
    $("select[name=state]").attr("id", "stateId")
    $("select[name=state]").addClass("states")
    $("select[name=city]").attr("id", "cityId")
    $("select[name=city]").addClass("cities")
</script>
<script src="//geodata.solutions/includes/countrystatecity.js"></script>
{% endblock %}

products/templates/cart/checkout_success.html
{% extends 'base.html' %} {% block title %}
<title>
    Checkout Success
</title>
{% endblock %}{% block body %}

<div class="row">
    <div class="col-lg-5 mx-auto">
        <div class="card prod-card">
            <div class="card-header">
                <h4>Checkout Success</h4>
            </div>
            <div class="card-body">
                <h4 class="text-center">Your order request has been sent</h4>
                <h6 class="text-center">Please check confirmation email</h6>
                <h6 class="text-center">Your order id is</h6>
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <input type="text" readonly value="{{order_id}}" class="form-control">
                    </div>
                </div>
                <div class="text-center my-4">
                    <a href="https://mail.google.com/mail/u/0/#inbox" class="btn btn-secondary">Check Confirmation Email</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}