products/urls.py
from django.conf.urls import url
from django.urls import path
from products import views
from products.utils import get_cart_data

app_name = "products"

urlpatterns = [
    path("products/", views.DashboardClient.as_view(), name="products"),
    path("products_list/", views.ProductListFilter.as_view(), name="products_api"),
    path("product_detail/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product_cat/", views.ProductCategoryApi, name="product_api"),
    path('get_book_products/',views.get_cart_data, name="book-products"),
    path('cart/', views.CartSystem, name='get-cart-api'),
    path('main-redirect/', views.MainRedirect.as_view(), name="main-redirect"),
    path('checkout/', views.OrderView.as_view(), name="checkout"),
    path('checkout-success/', views.checkout_success, name="checkout-success"),
    path('order-success/', views.Order_Success, name="order-success"),
    path('reset_cart/',views.reset_cart, name="reset-cart"),
    path('delete_cart_product/<int:id>/',views.DeleteSingleProduct, name="delete-cart-product"),
    path('order-list-template/', views.OrderListTemplate, name="order-list-template"),
    path('order-list-api/',views.Order_List, name="order-list-api"),
    path('order-detail-template/<int:pk>/<str:order_id>', views.OrderDetailTemplate, name="order-detail-template"),
    path('order-detail-api/<int:pk>/<str:order_id>',views.OrderDetailApi, name="order-detail-api"),
    path('order-status/',views.OrderStatusUpdate, name="order-status"),
    path('order-status-form/<str:pk>/',views.OrderStatus, name="order-status-form"),
    path('product-api/',views.products_api, name="product-api"),
    path('product-list-template/',views.product_list_template, name="product-list-template"),
    path('create-product/',views.CreateProduct.as_view(), name="create-product"),
    path('delete-product/<int:pk>',views.ProductDelete, name="delete-product"),
    path('update-product/<int:pk>',views.UpdateProduct.as_view(), name="update-product"),
    # path('test/<str:id>/',views.test_view, name="test-view"),
    
    path('order-request-template/',views.OrderRequestTemplate, name="order-request-template"),
    path('order-request-api/',views.Order_Request, name="order-request-api"),
    
    path('pending-orders-list/',views.PendingOrderListTemplate, name="pending-order-template"),
    path('pending-orders-api/',views.PendingOrderApi, name="pending-order-api"),
    
    path('delievered-orders-list/',views.DelieveredOrderListTemplate, name="delievered-orders-template"),
    path('delievered-orders-api/',views.DelieveredOrderApi, name="delievred-orders-api"),
    
    path('order-request-form/',views.OrderRequestForm, name="order-request-form"),
    path('order-request-status/',views.OrderRequestStatus, name="order-request-status"),
    
    path('send-return-email/',views.SendReturnEmailList, name="send-return-email"),
    path('items-list/',views.ItemListApi, name='item-list-api'),
    path('send-email-form/',views.SendEmailForm, name='send-email-form'),
    path('send-email/', views.SendReturnEmail, name='send-email'),
    
    path('OrderCountGraphApi/',views.OrderCountGraphApi, name="order-graph-api"),
    
    #unused
    # path('api-overview/', views.api_overview, name="api-overview"),
    path('product-api/',views.Order_List, name="product-api"),
    path('product-detail/<str:pk>/',views.products_api, name="product-detail"),
]

rent_pro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('users.urls', namespace="users"), name="users"),
    # path('',RedirectView.as_view(url='/accounts/login/')),
    path('',RedirectView.as_view(url='/users/products/')),
    path('users/',include('products.urls', namespace="products"), name="products"),
    path('payments/',include('payments.urls', namespace="payments"), name="payments"),

    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("login/",auth_views.LoginView.as_view(template_name="login.html", redirect_authenticated_user=True), name="login" ),
    path("profile/",views.UpdateProfile.as_view(), name="profile" ),
    path("register/",views.RegisterUser.as_view(), name="register" ),
    path("logout/",auth_views.LogoutView.as_view(), name="logout" ),
    path("admin_dashboard/",views.AdminDashboard.as_view(), name="admin-dashboard"),
    path("user_list_template/",views.UserListTemplate.as_view(), name="user-list-template"),
    path("user_list/",views.User_List, name="user-list-api"),
    path("user_list_graph_api/",views.User_List_Graph, name="user-list-graph-api"),
]

products/forms.py
from django import forms
from django.db.models import fields
from django.db.models.enums import Choices
from django.forms import ModelForm
from products import models

class CategoryForm(ModelForm):
    class Meta:
        model = models.Product
        fields = ["prod_cat","prod_sub"]
        
class OrderForm(ModelForm):
    country = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    state = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    city = forms.ChoiceField(label="",
                                initial='',
                                widget=forms.Select(),
                                required=True)
    class Meta:
        model = models.Order
        fields = ["address","email","total_amount","deliever_at","country","state","city","zip_code",'your_bid_total']
        required = "__all__"
class OrderDelieveryStatusForm(ModelForm):
    class Meta:
        model = models.Order
        fields = ["status"]
        
class ProductForm(ModelForm):
    class Meta:
        model = models.Product
        exclude = ["timePeriod"]
        
class OrderStatusForm(ModelForm):
    class Meta:
        model=models.Order
        fields=['is_accepted']

products/views.py
import re
from django.core import paginator
from django.db.models import query
from django.http.response import Http404, HttpResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView, View
from django.views.generic import ListView,FormView,DetailView
from django.views.generic.edit import CreateView, UpdateView
from .models import Category, Product, Sub_Category,Cart, Order
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CategoryForm,OrderForm,OrderStatusForm,ProductForm,OrderStatusForm,OrderDelieveryStatusForm
from django.http import HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.utils.http import urlencode
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from django.core import serializers
from django.http import JsonResponse
from django.conf import settings
from django.core.mail import send_mail,EmailMultiAlternatives
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import CartSerializer, OrderGraphSerializer, ProductSerializer,OrderSerializer,OrderRequestSerializer
from django.core.exceptions import PermissionDenied
from django.db.models import Q
import uuid
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from notifications.signals import notify
from django.contrib.auth import get_user_model
from datetime import datetime
from datetime import timedelta
from django.db.models.functions import Cast, Trunc
from django.db.models import (Q, 
                            Sum, 
                            F, 
                            Max, 
                            Min,
                            Count,
                            Value,
                            ExpressionWrapper, 
                            DurationField,
                            DecimalField, 
                            DateField,
                            DateTimeField, 
                            TimeField)

# Create your views here.
User = get_user_model()
class MainRedirect(LoginRequiredMixin, View):
    def get(self,request, *args, **kwargs):
        print(self.request.user.user_role)
        if self.request.user.user_role=='Admin':
            return HttpResponseRedirect(reverse('users:admin-dashboard'))
        return HttpResponseRedirect(reverse('products:products'))    


class DashboardClient(FormView):
    template_name="product/dashboard_client.html"
    form_class = CategoryForm
    model = Category


    def get_querylist(self,**kwargs):
         query_list = {
                "product_list":kwargs['product_list'],
                "product":kwargs["product"]
            }
         return query_list

    def get_queryset(self):
        product_list = Product.objects.all()
        page = self.request.GET.get('page',1)
        paginator = Paginator(product_list, 10)
        query_list = {}
        try:
            query_list = self.get_querylist(product_list=product_list, product=paginator.page(page))

        except PageNotAnInteger:
            query_list=self.get_querylist(product_list=product_list, product=paginator.page(1))

        except EmptyPage:
            query_list=self.get_querylist(product_list=product_list, product=paginator.page(paginator.num_pages))

        return query_list
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("**querlist starts")
        print(self.get_queryset())
        print("**querylist ends")
        context["products"]=self.get_queryset()["product"]
        context["product_list"]=serializers.serialize("json",self.get_queryset()["product_list"])
        print(self.get_queryset())
        return context
    
    def post(self, request, *args, **kwargs):
        category = self.request.POST.get('category')
        sub_category = self.request.POST.get('sub_category')
        query_params = {
            'category':category,
            'sub_category':sub_category
        }   
        return HttpResponseRedirect(reverse_lazy('products:products_api')+f'?{urlencode(query_params)}')
    
    

def ProductCategoryApi(request):
        sub_category = Sub_Category.objects.values_list("category__cat_name","sub_category")
        print(sub_category)
        dct = dict((y,x) for x,y in sub_category)
        lst_dct = {}
        # lst_dct['Furniture'] = [k for k, v in dct.items() if v == 'Furniture']
        # lst_dct['ElectricAppliances'] = [k for k, v in dct.items() if v == 'ElectricAppliances']
        # lst_dct['FitnessEquipment'] = [k for k, v in dct.items() if v == 'FitnessEquipment']
        # lst_dct['Crockery'] = [k for k, v in dct.items() if v == 'Crockery']
        for k,v in dct.items():
            lst_dct[v] = [i for i,j in dct.items() if j == v]
        print(lst_dct)
        print("****************")
        print(dct)
        print("****************")
        print(lst_dct['Furniture'])
        
        return JsonResponse(lst_dct, safe=False)
          
class ProductListFilter(ListView):
    template_name="product/dashboard_client.html"
    def get_queryset(self):

        if self.request.method=="GET":
            query_set = {}
            cat = self.request.GET.get('category',None)
            sub_cat = self.request.GET.get('sub_category',None)
            
            if cat is not None and sub_cat is not None:
                query_set = Product.objects.filter(prod_cat__cat_name__contains=cat,prod_sub__sub_category__contains=sub_cat)
                return query_set
        return query_set
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["products"] = self.get_queryset()
        return context
    
class ProductDetailView(LoginRequiredMixin,DetailView):
    template_name="product/product_detail.html"
    model = Product
    
def get_cart_data(request):
    if request.method == 'POST':
        request_getdata = request.POST.get('data_dict', None)
        request_getdata = json.loads(request_getdata)
        print()
        cart_obj = Cart.objects.create(user=request.user)
        prod_obj = Product.objects.get(product_name=request_getdata['prod_name'])
        prod_obj.product_quantity = prod_obj.product_quantity - request_getdata['quantity']
        return_date = (datetime.now() + timedelta(days=request_getdata['days']+1)).strftime('%Y-%m-%d')
        cart_obj.product_name=request_getdata['prod_name']
        cart_obj.product_category=request_getdata['prod_cat']
        cart_obj.product_subcategory=request_getdata['prod_sub']
        cart_obj.total_price=request_getdata['total_price']
        cart_obj.quantity = request_getdata['quantity']
        cart_obj.your_bid_price = request_getdata['your_bid_price']
        cart_obj.order_id = "hello"
        cart_obj.return_date = return_date
        
        cart_obj.save()
        prod_obj.save()
        return JsonResponse({'url':reverse('products:get-cart-api')})
    
class OrderView(LoginRequiredMixin,View):
    form_class = OrderForm
    model = Order
    
    def get(self, *args, **kwargs):
        context = {
            'form':self.form_class,
            'total_amount':self.get_queryset()['total_price'],
            'total_bid_price':self.get_queryset()['total_bid_price'],
            'success_url':self.get_success_url()
        }
        return render(self.request, 'cart/checkout.html', context)
    
    def get_queryset(self,*args,**kwargs):
        qs = Cart.objects.filter(user=self.request.user, is_checkout=False).values('total_price','your_bid_price')
        context = {
        "total_price":0,
        "total_bid_price" :0
        }
        print(qs)
        for i in qs:
            context['total_price']+=i['total_price']
            context['total_bid_price']+=i['your_bid_price']
        return context

    def get_success_url(self,*args,**kwargs):
        return reverse_lazy('products:order-success')
    
@login_required
def Order_Success(request):
    if request.method == "POST":
        uni_id = uuid.uuid4()
        order_obj = Order.objects.create()
        print(uni_id)
        cart_obj = Cart.objects.filter(user=request.user,is_checkout=False).update(is_checkout=True,order_id=uni_id)
        order_obj.order_id = uni_id
        order_obj.user = request.user
        order_obj.email = request.POST.get('email')
        order_obj.address = request.POST.get('address')
        order_obj.total_amount = request.POST.get('total_amount')
        order_obj.deliever_at = request.POST.get('deliever_at')
        order_obj.country = request.POST.get('country')
        order_obj.state = request.POST.get('state')
        order_obj.city = request.POST.get('city')
        order_obj.zip_code = request.POST.get('zip_code')
        order_obj.your_bid_total = request.POST.get('your_bid_total')
        order_obj.save()
        user_obj = User.objects.get(user_role='Admin')
        print(user_obj)
        notify.send(request.user, recipient=user_obj, verb='Notification', description=f'Order Request from {request.user.email}')

        subject, from_email, to = 'Booking Request', settings.EMAIL_HOST_USER, request.user.email
        text_content = ''
        html_content = f'<h1>Booking Request Email</h1> <h2>{request.user} Your booking request has been sent<h2>'
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        subject, from_email, to = 'New Booking Request', settings.EMAIL_HOST_USER, settings.EMAIL_HOST_USER
        text_content = ''
        html_content = f'<h1>Booking Request Email</h1> <h2>You have received Booking Request from {request.POST.get("email")}<h2> <p><b>Order Id : </b>{uni_id}<p>'

products/templates/product/dashboard_client.html
{% extends 'base.html' %} {% block title %}
<title>Products</title>
{% endblock %}{% block body %}

<div class="row d-flex flex-row ms-1">
    <!-- <div class="col-lg-9"></div> -->
    <div class="col-lg-3 ms-2 py-2 search-card">
        <form action="{% url 'products:products' %}" method="POST">
            <h4>Select Category</h4>
            <hr> {% csrf_token %}
            <div class="col-lg-8">
                <select name="category" id="category" class="category form-select" aria-label="Default select example">
                <option value="category">Select Category</option>
            </select>
            </div>
            <div class="col-lg-8 mt-3">
                <select name="sub_category" id="sub_category" class="sub_category form-select" aria-label="Default select example">
                <option value="category">Select Sub-Category</option>
            </select>
            </div>
            <div class="ms-3 mt-3">
                <button type="submit" class="btn btn-success">Search</button>
            </div>
        </form>
    </div>
</div>
<div class="row">

    {% if products|length > 0 %} {% for i in products %}
    <div class="col-lg-4 my-3">
        <div class="card-group">
            <div class="card prod-card login-card">
                <img src="{{i.prod_img.url}}" class="card-img-top" alt="{{i.product_name}}" style="height: 300px;">
                <div class="card-body">

                    <h5 class="card-title">{{i.product_name}}</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                </div>
                <div class="card-footer">
                    {% if i.product_quantity > 0 %}
                    <a href="{% url 'products:product_detail' i.id %}" class="btn btn-primary">Book Now</a> {% else %}
                    <p class="text-danger">Out of stock</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script>
    </script>
    {% endfor %}
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        {% if products.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span>&laquo;</span></li>
        {% endif %} {% for i in products.paginator.page_range %} {% if products.number == i %}
        <li class="page-item active"><a class="page-link" href="">{{i}} (current)</a>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %} {% endfor %} {% if products.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
{% else %}
<h1 class="text-start">No Product Found of such filter</h1>
{% endif %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.22.0/axios.min.js" integrity="sha512-m2ssMAtdCEYGWXQ8hXVG4Q39uKYtbfaJL5QMTbhl2kc6vYyubrKHhr6aLLXW4ITeXSywQLn1AhsAaqrJl8Acfg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    var list = "{% url 'products:product_api' %}"
    var category = document.getElementById("category")
    var sub_category = document.getElementById("sub_category")
    var sub_cat = []
    var cat = [];


    function populate_subcategory(cat, select_value) {
        if (select_value) {
            for (var f of cat) {
                let createEle = document.createElement("option")
                createEle.value = f
                createEle.textContent = f
                sub_category.appendChild(createEle)
            }
        }
    }

    function removeOptions(selectElement) {
        var i, L = selectElement.options.length - 1;
        for (i = L; i >= 0; i--) {
            selectElement.remove(i);
        }
    }

    axios.get(list)
        .then((data) => {
            cat = Object.keys(data.data)
            cat.forEach((val, ind) => {
                $(".category").append(`<option value=${val}>${val}</option>`)
            })
            $(".category").on("change", function() {
                var cat_value = $(this).val()
                removeOptions(sub_category);
                populate_subcategory(data.data[cat_value], cat_value)
            })

        })
        .catch(err => console.log(err))
</script>


{% endblock %}

products/templates/product/product_detail.html
{% extends 'base.html' %} {% block title %}
<title>Product Detail</title>
{% endblock %} {% block body %}
<div class="row my-2">
    <div class="col-lg-10 mx-auto">
        <div class="card prod-card login-card mb-3">
            <div class="row g-0">
                <div class="col-md-5">
                    <img src="{{product.prod_img.url}}" class="img-fluid rounded-start" alt="{{product.product_name}}" style="height:540px; width: 100%;">
                </div>
                <div class="col-md-7">
                    <div class="card-body">
                        <div>
                            {% csrf_token %}
                        </div>
                        <h5 class="card-title">{{product.product_name}}</h5>
                        <p class="card-text">{{product.product_desc}}</p>
                        <h4>TimePeriod : <i class="fa fa-plus add-time text-dark" aria-hidden="true"></i> <span class="timeperiod">{{product.timePeriod}}</span> <i class="fa fa-minus text-dark sub-time" aria-hidden="true"></i><span class="text-muted mx-2"
                                style="font-size: 1rem;">*in days</span></h4>
                        <h4>Quantity : <i class="fa fa-plus add-qty text-dark" aria-hidden="true"></i> <span class="quantity">1</span> <i class="fa fa-minus text-dark sub-qty" aria-hidden="true"></i></h4>
                        <h4 class="mt-3">Price : pkr <span class="price">{{product.product_price}}</span> <span class="text-muted" style="font-size: 1rem;">for <span class="week"></span> days</span>
                        </h4>
                        <h4 class="mt-3">Your Bid </h4>
                        <input type="number" placeholder="Place your bid" name="your_bid" class="form-control col-lg-4">
                        <small class="text-muted">If you leave this field blacnk, we will consider original price mentioned above</small>
                        <div class="text-end">
                            <span class="tag text-center mx-3">
                                {{product.prod_cat}}
                            </span>
                            <span class="tag text-center">
                                {{product.prod_sub}}
                            </span>
                        </div>
                    </div>
                    <div class="card-footer mt-5">
                        <button class="btn btn-primary mt-3 book-btn" style="width: 100%">Book Now</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    let csrf_token = $("input[name=csrfmiddlewaretoken]").val()
    let baseurl = window.location.origin
    console.log(baseurl)
    let prod_dict = {
        prod_name: "{{product.product_name}}",
        prod_cat: "{{product.prod_cat}}",
        prod_sub: "{{product.prod_sub}}",
        total_price: parseFloat($(".price").text()),
        quantity: 1,
        your_bid_price: 0,
        days: 1
    }
    let timepr;
    let quantity;
    let prod_price;
    let orig_price = parseFloat($(".price").text())
    $(".sub-time").addClass("d-none")
    $(".sub-qty").addClass("d-none")
    $(".week").text($(".timeperiod").text())
    $(".add-time").on("click", function() {
        timepr = parseInt($(".timeperiod").text())
        timepr += 1
        $(".week").text(timepr)
        $(".timeperiod").text(timepr)
        quantity = parseInt($(".quantity").text())
        prod_price = parseFloat($(".price").text())
        prod_price = (orig_price * timepr) * quantity
        $(".price").text(prod_price)
        prod_dict['total_price'] = prod_price
        prod_dict['days'] = timepr
        if (parseInt($(".timeperiod").text()) > 1) {
            $(".sub-time").removeClass("d-none")
        } else {
            $(".sub-time").addClass("d-none")
        }
    })


    $(".sub-time").on("click", function() {
        timepr = parseInt($(".timeperiod").text())
        timepr -= 1
        $(".timeperiod").text(timepr)
        $(".week").text(timepr)
        quantity = parseInt($(".quantity").text())
        prod_price = parseFloat($(".price").text())
        prod_price = (prod_price - orig_price) * quantity
        $(".price").text(prod_price)
        prod_dict['total_price'] = prod_price
        prod_dict['days'] = timepr
        if (parseInt($(".timeperiod").text()) > 1) {
            $(".sub-time").removeClass("d-none")
        } else {
            $(".sub-time").addClass("d-none")
        }
    })

    $(".add-qty").on("click", function() {
        timepr = parseInt($(".timeperiod").text())
        quantity = parseInt($(".quantity").text())
        quantity += 1
        $(".quantity").text(quantity)
        prod_price = parseFloat($(".price").text())
        prod_price = (orig_price * timepr) * quantity
        $(".price").text(prod_price)
        prod_dict['total_price'] = prod_price
        prod_dict['quantity'] = quantity

        if (parseInt($(".quantity").text()) > 1) {
            $(".sub-qty").removeClass("d-none")
        } else {
            $(".sub-qty").addClass("d-none")
        }
    })

    $(".sub-qty").on("click", function() {
        quantity = parseInt($(".quantity").text())
        timepr = parseInt($(".timeperiod").text())
        quantity -= 1
        $(".quantity").text(quantity)
        prod_price = parseFloat($(".price").text())
        console.log(prod_price)
        prod_price = (orig_price * quantity) * timepr
        $(".price").text(prod_price)
        prod_dict['total_price'] = prod_price
        prod_dict['quantity'] = quantity
        if (parseInt($(".quantity").text()) > 1) {
            $(".sub-qty").removeClass("d-none")
        } else {
            $(".sub-qty").addClass("d-none")
        }
    })

    $("input[name=your_bid]").on("change", function() {
        prod_dict['your_bid_price'] = parseInt($(this).val())
        console.log(prod_dict)
    })

    $(".book-btn").on("click", function() {
        console.log(prod_dict)
        $.ajax({
            url: `${baseurl}/users/get_book_products/`,
            method: "POST",
            "headers": {
                "accept": "application/json",
                "Access-Control-Allow-Origin": "*"
            },
            data: {
                'data_dict': JSON.stringify(prod_dict),
                'csrfmiddlewaretoken': csrf_token
            },
            dataType: 'json',
            success: function(url) {
                window.location.href = baseurl + url['url']
            }
        })
    })
</script>
{% endblock %}

products/templates/product/product_list.html
{% extends 'base.html' %} {% block title %}
<title>
    Product LIst
</title>
{% endblock %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}"> {% endblock %} {% block js %} {% endblock %} {% block body %}
<div class="preview-sec mt-3">
    <div class="row">
        <div class="col-lg-12 login-card">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="text-center pt-2">Products</h3>
                </div>
            </div>
            <hr>
            <div class="form-group col-lg-2">
                <img src="{% static 'images/more_options.png' %}" class="toggle-options" width="30%" height="50%" alt="" title="More Options" style="cursor: pointer;">
            </div>
            <div class="options">
                <div class="form-group col-lg-2">
                    <select name="export-cols" id="exportLink" class="form-control">
                <option>Export Data</option>
                <option id="copy">Copy to clipboard</option>
                <option id="excel">Export as Excel</option>
                <option id="csv">Export as CSV</option>
                <option id="print">Export as Print</option>
              </select>
                </div>
                <!-- <div class="form-group col-lg-2">
                      <a class="btn submit-btn" id="imputation">Imputation</a>
                  </div> -->
            </div>
            <span class="loader my-3"></span>
            <table id="dtproduct_list" name="dtproduct_list" class="display table table-hover table-borderless dt-responsive table-responsive-lg nowrap" width="100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Product Name</th>
                        <th>Product Category</th>
                        <th>Product SubCategory</th>
                        <th>Product Price</th>
                        <th>Quantity</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="orders-data">

                </tbody>
            </table>
        </div>

    </div>
</div>
<script type="text/javascript">
    let dateCol = 4;
    let expArr = [0, 1, 2, 3, 4, 5];
    let tableId = '#dtproduct_list';
    apiUrl = '{% url "products:product-api" %}';
    let responseArrCols = [{
        "data": "id"
    }, {
        "data": "product_name"
    }, {
        "data": "prod_cat"
    }, {
        "data": "prod_sub"
    }, {
        "data": "product_price"
    }, {
        "data": "product_quantity"
    }, {
        mRender: function(data, type, row) {
            let delUrl = '{% url "products:delete-product" 123 %}'.replace('123', row['id'])
            let editUrl = '{% url "products:update-product" 123 %}'.replace('123', row['id'])
            return `<a class="table-edit" href=${editUrl}><i class="fas fa-user-edit font-weight-bold"></i></a> <a class="table-delete" href=${delUrl}><i class="fas fa-trash text-danger font-weight-bold"></i></a>`
        }
    }, ];

    loadRecordsInDataTable(dateCol, expArr, apiUrl, responseArrCols, tableId);
</script>
{% endblock %}